go: update golang.org/x/text to 0.3.8
flatcar/flatcar-linux-update-operator pull request #189
Opened 2023-02-22 09:26 UTC by dongsupark

Update `golang.org/x/text` to 0.3.8 mainly to address [CVE-2022-32149](https://nvd.nist.gov/vuln/detail/CVE-2022-32149).

## Testing done

Local build passed

- Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)

2023-02-22 10:25 UTC, invidian requested changes

2023-02-22 10:25 UTC, invidian commented on Makefile
> +	go mod tidy -compat=1.17
I think we can update directly to `v0.7.0` and skip the whole dance with compatibility.

2023-02-22 10:53 UTC, dongsupark commented on Makefile
> +	go mod tidy -compat=1.17
Updated directly to v0.7.0, but still the CI fails at `go mod tidy`.

2023-02-23 10:01 UTC, invidian commented on Makefile
> +	go mod tidy -compat=1.17
Thanks. Let me figure out why CI still complains.

2023-02-23 11:23 UTC, closed without merging